services:
  postgres:
    image: 'postgres:16-alpine'
#    volumes:
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgresr'
    ports:
      - '8432:5432'
